name: Every 10 Minutes Update
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium aiohttp asyncio requests[socks]
    - name: Run
      run: |
        python scraper.py
        python checker.py
        python readme.py
    - name: Commit
      run: |
        set -e
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        d="$(date --rfc-3339=s)"
        git add --all
        git commit --allow-empty -m "Update 📦 $d"
        git push -f origin main